This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/Users/Daniel/Documents/1 current projects/Bachelorarbeit/0 - Entwürfe/0.01/sample.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file sample.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file sample.acr....done (6 lines written, 0 warnings).
Output written in sample.acr.
Transcript written in sample.alg.
